{
 "title": "I. GitHub Classic",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT pm.project_name  \nFROM project_mapping pm \nWHERE pm.`table` = 'repos' AND pm.row_id like 'github:%'\nORDER BY pm.project_name "
   },
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "SELECT CONCAT(r.name, '--', r.id) AS text \nFROM project_mapping pm \nJOIN repos r ON r.id = pm.row_id \nWHERE pm.`table` = 'repos' AND pm.row_id like 'github:%'\nAND pm.project_name IN ( $project )\nORDER BY text"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic Git and Code Review metrics from GitHub.\n- Data Source Required: GitHub"
   }
  },
  { "title": "1. User Requirements (Issues)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "1.1 Number of New Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tcount(distinct i.id)\nfrom \n\tissues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  $__timeFilter(i.created_date)\n  and b.id in (${repo_id})\n"
    }
   ]
  },
  {
   "title": "1.2 Number of New Issues",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 4 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.created_date), INTERVAL -$interval(date(i.created_date))+1 DAY) as time,\n    count(distinct i.id) as issue_count\n  FROM issues i\n  \tjoin board_issues bi on i.id = bi.issue_id\n  \tjoin boards b on bi.board_id = b.id\n  WHERE\n    $__timeFilter(i.created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and b.id in (${repo_id})\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  issue_count as \"Issue Count\"\nFROM _issues\nORDER BY time\n"
    }
   ]
  },
  { "title": "2. How issues are handled?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "2.1 Number of Closed Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tcount(distinct i.id)\nfrom \n\tissues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  $__timeFilter(i.created_date)\n  and b.id in (${repo_id})\n  and i.status = \"DONE\"\n\n\n"
    }
   ]
  },
  {
   "title": "2.2 Number of open and closed issues by Issue creation time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 11 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.created_date), INTERVAL -$interval(date(i.created_date))+1 DAY) as time,\n    count(distinct case when status != 'DONE' then i.id else null end) as open_issue_count,\n    count(distinct case when status = 'DONE' then i.id else null end) as closed_issue_count\n  FROM issues i\n    join board_issues bi on i.id = bi.issue_id\n    join boards b on bi.board_id = b.id\n  WHERE\n    $__timeFilter(i.created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and b.id in (${repo_id})\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  open_issue_count,\n  closed_issue_count\nFROM _issues\nORDER BY time"
    }
   ]
  },
  {
   "title": "2.3 Mean Issue Lead Time by issue resolution time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tAVG(i.lead_time_minutes/1440) issue_lead_time_in_days\nfrom \n\tissues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  $__timeFilter(i.resolution_date)\n  and i.resolution_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  and b.id in (${repo_id})\n  and i.status = \"DONE\""
    }
   ]
  },
  {
   "title": "2.4 Mean issue lead time by issue resolution time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.resolution_date), INTERVAL -$interval(date(i.resolution_date))+1 DAY) as time,\n    AVG(i.lead_time_minutes/1440) as issue_lead_time\n  FROM issues i\n  \tjoin board_issues bi on i.id = bi.issue_id\n  \tjoin boards b on bi.board_id = b.id\n  WHERE\n    b.id in (${repo_id})\n    and i.status = \"DONE\"\n    and $__timeFilter(i.resolution_date)\n    and i.resolution_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  issue_lead_time as \"Mean Issue Lead Time in Days\"\nFROM _issues\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "2.5 Top 20 Queue Time [All Open Issues]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "-- Get the queue time of all outstanding bugs\nwith _outstanding_issues as(\n  select \n    DISTINCT\n    b.name as repo_name,\n    i.issue_key,\n    i.title,\n    i.created_date,\n    (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as queue_time_in_days,\n    concat(b.url,'/',i.issue_key) as url\n  from \n    issues i\n    left join board_issues bi on i.id = bi.issue_id\n    left join boards b on bi.board_id = b.id\n  where\n    b.id in (${repo_id})\n    and $__timeFilter(i.created_date)\n    and i.status != 'DONE'\n)\n\nselect concat('#', issue_key) as issue_key, title, url, queue_time_in_days from _outstanding_issues\norder by 4 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "2.6 List of Outstanding Issues Order By Queue Time [All Open Issues]",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Get the queue time of all outstanding bugs\nselect \n  b.name as repo_name,\n  i.issue_key as issue_key,\n  i.title,\n  i.created_date,\n  (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as queue_time_in_days,\n  concat(b.url,'/',i.issue_key) as url\nfrom \n  issues i\n  left join board_issues bi on i.id = bi.issue_id\n  left join boards b on bi.board_id = b.id\nwhere\n  b.id in (${repo_id})\n  and $__timeFilter(i.created_date)\n  and i.status != 'DONE'\norder by queue_time_in_days desc"
    }
   ]
  },
  { "title": "3. Contribution (PRs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "3.1 Number of New Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(distinct pr.id) as pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand is_draft = false\n\t\n\n"
    }
   ]
  },
  {
   "title": "3.2 Number of New Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct id) as pr_count\n  FROM pull_requests\n  WHERE\n    base_repo_id in (${repo_id})\n    and $__timeFilter(created_date)\n    and is_draft = false\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  pr_count as \"Pull Request Count\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "3.3 Top 20 Contributors By Merged PRs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  author_name,\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and pr.status = 'MERGED'\n  and is_draft = false\ngroup by 1\norder by 2 desc\nlimit 20\n"
    }
   ]
  },
  { "title": "4. How PRs are handled?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "4.1 Ratio of unmerged PRs of All Closed PRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand is_draft = false"
    }
   ]
  },
  {
   "title": "4.2 Pull Request Status Distribution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 49 },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nwith _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct case when status = 'OPEN' then id else null end) as open,\n    count(distinct case when status = 'CLOSED' then id else null end) as closed,\n    count(distinct case when status = 'MERGED' then id else null end) as merged\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n    and is_draft = false\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  open as \"PR: Open\",\n  closed as \"PR: Closed without merging\",\n  merged as \"PR: Closed and merged\"\nFROM _prs\nORDER BY time"
    }
   ]
  },
  {
   "title": "4.3 Number of PRs Closed without Merging",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand pr.status = 'CLOSED'\n\tand is_draft = false"
    }
   ]
  },
  {
   "title": "4.4 Ratio of unmerged PRs of All Closed PRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nFROM pull_requests\nWHERE\n  $__timeFilter(created_date)\n  and base_repo_id in (${repo_id})\n  and is_draft = false\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "4.5 Mean Time to Merge of Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440)\nfrom \n\tpull_requests\nwhere \n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand merged_date is not null\n\tand is_draft = false\n\n\n"
    }
   ]
  },
  {
   "title": "4.6 Mean Time to Merge of Pull Requests in Days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 61 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440) as time_to_merge\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n    and is_draft = false\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  time_to_merge as \"Time to Merge\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "4.7 Mean Time to Close of Pull Requests in Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\nfrom \n\tpull_requests\nwhere \n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand status in ('CLOSED', 'MERGED')\n\tand is_draft = false\n\n\n"
    }
   ]
  },
  {
   "title": "4.8 Mean Time to Close of Pull Requests in Days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 67 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n    and status in ('CLOSED', 'MERGED')\n    and is_draft = false\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  time_to_close as \"Time to Close\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  { "title": "5. CI/CD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "5.1 Total Number of Successful workflow runs",
   "type": "stat",
   "description": "Number of workflow runs executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM \n  cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and result = 'SUCCESS'\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.2 Mean Workflow Runs Success Rate",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * count(case when result = 'SUCCESS' then id else null end)/count(distinct id)\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.3 Number of successful and failed workflow runs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "rawSql": "with _workflow_runs as (\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    count(distinct case when result = 'SUCCESS' then id else null end) as successful_workflow_run_count,\n    count(distinct case when result != 'SUCCESS' then id else null end) as failed_workflow_run_count\n  FROM cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    and id like \"%github%\"\n    and cicd_scope_id in (${repo_id})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  successful_workflow_run_count,\n  failed_workflow_run_count\nFROM _workflow_runs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "5.4 Total Workflow Runs Result Distribution",
   "type": "piechart",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  IF(result = '', 'Unknown', result) as result,\n  count(distinct id) as build_count\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\nGROUP BY 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "5.5 Workflow Runs Success Rate",
   "type": "barchart",
   "description": "1. Mean Workflow Runs success rate over time.\n2. The workflow runs being calculated are filtered by \"workflow runs starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\r\n    result,\r\n    id\r\n  FROM\r\n    cicd_pipelines\r\n  WHERE\r\n    $__timeFilter(finished_date)\r\n    and id like \"%github%\"\r\n    and cicd_scope_id in (${repo_id})\r\n    -- Enable the following condition to remove the month with incomplete data\r\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\r\n  GROUP BY \r\n    time, result, id\r\n)\r\n\r\nSELECT \r\n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%m/%Y') else concat('W', date_format(time,'%u %Y')) end as _time,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Workflow Runs Success Rate\"\r\nFROM _build_success_rate\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "5.6 Mean Workflow Runs Duration",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(duration_sec/60) as duration_in_minutes\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.7 Mean Workflow Runs Duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH _builds as(\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    avg(duration_sec) as mean_duration_sec\n  FROM \n    cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    and id like \"%github%\"\n    and cicd_scope_id in (${repo_id})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  mean_duration_sec\nFROM _builds\nORDER BY time\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   }
  },
  { "title": "6. Draft PRs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Draft PR Count",
   "type": "stat",
   "description": "Number of open draft PRs created in the selected time range",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(distinct pr.id) as \"Draft PR Count\"\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand is_draft = true\n\tand status = 'OPEN'\n"
    }
   ]
  },
  {
   "title": "6.1 Open Draft PRs Over Time",
   "type": "barchart",
   "description": "Number of open draft PRs created over time",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct id) as draft_pr_count\n  FROM pull_requests\n  WHERE\n    base_repo_id in (${repo_id})\n    and $__timeFilter(created_date)\n    and is_draft = true\n    and status = 'OPEN'\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  draft_pr_count as \"Open Draft PR Count\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "6.2 Top Contributors with Open Draft PRs",
   "type": "table",
   "description": "Top contributors with open draft PRs in the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
   "targets": [
    {
     "rawSql": "select\n  author_name as \"Author Name\",\n\tcount(distinct pr.id) as \"Open Draft PR Count\"\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and is_draft = true\n  and status = 'OPEN'\ngroup by 1\norder by 2 desc\nlimit 20\n"
    }
   ]
  },
  {
   "title": "7. Test Cases Coverage Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
  },
  {
   "title": "7.1 Aggregate Unit Test Coverage",
   "type": "stat",
   "description": "Aggregate CQTest coverage across all selected GitHub repos, based on SonarQube file metrics. Matches SonarQube projects by full repo name (e.g. \"owner/repo\") with fallback to the repo slug (\"repo\") for projects registered without an org prefix; project IDs are deduplicated so a slug-keyed project shared across selected repos is counted once. Filtered by file metric update time.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- CQTest coverage from SonarQube file metrics.\n-- Match selected repos to SonarQube projects by full name first, falling back to the\n-- repo slug. Project IDs are deduplicated via the _matched CTE so each project's file\n-- metrics are counted at most once -- even when the slug fallback would otherwise\n-- attach a single SonarQube project to multiple selected repos sharing a slug.\nwith _matched as (\n  select distinct cqp.id as project_key\n  from cq_projects cqp\n  join repos r\n    on r.name = cqp.name\n    or substring_index(r.name, '/', -1) = cqp.name\n  where r.id in (${repo_id})\n)\nselect\n  round(\n    (sum(fm.lines_to_cover) - sum(fm.uncovered_lines)) * 100.0\n    / nullif(sum(fm.lines_to_cover), 0),\n    1\n  ) as \"Unit Test Coverage %\"\nfrom\n  _matched m\n  join cq_file_metrics fm on fm.project_key = m.project_key\nwhere\n  $__timeFilter(fm.updated_at)"
    }
   ]
  },
  {
   "title": "7.2 PR Unit Test Coverage Details",
   "type": "table",
   "description": "Per-PR coverage view from SonarQube CQTest metrics. The Coverage % column reflects the SonarQube project's coverage at PR time -- exact PR-head-commit match where SonarQube scanned that commit (rare), otherwise the repository's most recent project status. Slug-fallback project matches are annotated in the Coverage Source column. Capped at 50 rows for performance.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 104 },
   "targets": [
    {
     "rawSql": "-- PR view with exact commit match first, then repository SonarQube project fallback.\n-- Match SonarQube projects by full repo name (\"owner/repo\") first, falling back to the\n-- repo slug for projects registered without an org prefix. Slug-fallback rows are\n-- annotated as such in the Coverage Source column.\n--\n-- The dashboard time range filters PR creation date only; coverage uses the latest\n-- available SonarQube data regardless of when the scan ran. Result is capped at 50\n-- rows ordered by PR creation date desc to keep the panel responsive on active repos.\nwith _selected_repos as (\n  select\n    r.id,\n    r.name as repo_name,\n    substring_index(r.name, '/', -1) as repo_slug\n  from repos r\n  where r.id in (${repo_id})\n),\n_project_coverage as (\n  select\n    cqp.id as project_key,\n    cqp.name,\n    cqp.commit_sha,\n    cqp.last_analysis_date,\n    cqp.updated_at as project_updated_at,\n    sr.repo_name,\n    case when cqp.name = sr.repo_name then 'full' else 'slug' end as match_type,\n    count(fm.id) as files,\n    sum(fm.lines_to_cover) as lines_to_cover,\n    sum(fm.uncovered_lines) as uncovered_lines\n  from\n    cq_projects cqp\n    join _selected_repos sr\n      on sr.repo_name = cqp.name\n      or sr.repo_slug = cqp.name\n    left join cq_file_metrics fm on fm.project_key = cqp.id\n  group by\n    cqp.id,\n    cqp.name,\n    cqp.commit_sha,\n    cqp.last_analysis_date,\n    cqp.updated_at,\n    sr.repo_name,\n    case when cqp.name = sr.repo_name then 'full' else 'slug' end\n),\n_repo_project as (\n  select\n    pc.*,\n    row_number() over(partition by pc.repo_name order by coalesce(pc.last_analysis_date, pc.project_updated_at) desc, pc.files desc, pc.project_key desc) as rn\n  from _project_coverage pc\n),\n_prs as (\n  select\n    pr.pull_request_key,\n    pr.title,\n    pr.author_name,\n    pr.status,\n    pr.created_date,\n    pr.url,\n    pr.head_commit_sha,\n    r.name as repo_name\n  from\n    pull_requests pr\n    join repos r on r.id = pr.base_repo_id\n  where\n    $__timeFilter(pr.created_date)\n    and pr.base_repo_id in (${repo_id})\n)\nselect\n  cast(pr.pull_request_key as unsigned) as \"PR Number\",\n  pr.title as \"PR Title\",\n  pr.author_name as \"Author\",\n  case upper(pr.status)\n    when 'OPEN' then 'Open'\n    when 'MERGED' then 'Merged'\n    when 'CLOSED' then 'Closed'\n    else pr.status\n  end as \"Status\",\n  pr.created_date as \"Created Date\",\n  pr.url as \"PR URL\",\n  coalesce(exact.project_key, rp.project_key) as \"SonarQube Project\",\n  case\n    when exact.project_key is not null then concat('PR commit match', case when exact.match_type = 'slug' then ' (slug)' else '' end)\n    when rp.project_key is not null then concat('Repo project fallback', case when rp.match_type = 'slug' then ' (slug)' else '' end)\n    else 'No SonarQube project'\n  end as \"Coverage Source\",\n  coalesce(exact.files, rp.files) as \"Files Scanned\",\n  coalesce(exact.lines_to_cover, rp.lines_to_cover) as \"Lines To Cover\",\n  round(\n    (coalesce(exact.lines_to_cover, rp.lines_to_cover) - coalesce(exact.uncovered_lines, rp.uncovered_lines)) * 100.0\n    / nullif(coalesce(exact.lines_to_cover, rp.lines_to_cover), 0),\n    1\n  ) as \"Repo Coverage at PR Time\",\n  case\n    when exact.project_key is null and rp.project_key is null then 'No SonarQube project matched this repo by full repo name or slug'\n    when exact.project_key is null then 'No PR commit match; showing repository SonarQube project status'\n    when coalesce(exact.lines_to_cover, rp.lines_to_cover) is null then 'No SonarQube file metrics'\n    when coalesce(exact.lines_to_cover, rp.lines_to_cover) = 0 then 'SonarQube imported files, but no LCOV lines_to_cover'\n    else 'Coverage available'\n  end as \"Coverage Data Status\"\nfrom\n  _prs pr\n  left join _project_coverage exact on exact.commit_sha = pr.head_commit_sha and exact.repo_name = pr.repo_name\n  left join _repo_project rp on rp.repo_name = pr.repo_name and rp.rn = 1\norder by\n  pr.created_date desc\nlimit 50"
    }
   ]
  }
 ]
}