{
 "title": "H. Jira - Legacy",
 "tags": [ "Data Source Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct upm.project_name\nfrom user_project_mapping upm \njoin project_mapping pm ON upm.project_name = pm.project_name \nWHERE pm.`table` = 'boards' AND pm.row_id like 'jira:%'\nand upm.user_login = ${__user.login:sqlstring}\nORDER BY upm.project_name "
   },
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "SELECT concat(b.name, '--', b.id) FROM boards b JOIN project_mapping pm ON pm.row_id = b.id AND pm.table = 'boards' WHERE b.id LIKE 'jira%' AND pm.project_name IN (${project})"
   },
   {
    "name": "assignee",
    "label": "Assignee",
    "query": "select distinct assignee_name from issues i join board_issues bi on i.id = bi.issue_id where bi.board_id in (${board_id}) and assignee_name != '' order by 1"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "select distinct type from issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic project management metrics from Jira.\n- Data Source Required: Jira"
   }
  },
  { "title": "1. Issue Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Number of Issues [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of issues created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  count(distinct i.id) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in (${type})\r\n  and $__timeFilter(i.created_date)\r\n  and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n  and i.assignee_name in (${assignee})"
    }
   ]
  },
  {
   "title": "Number of Delivered Issue [Issues Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  count(distinct i.id) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in (${type})\r\n  and i.status = 'DONE'\r\n  and $__timeFilter(i.created_date)\r\n  and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n  and i.assignee_name in (${assignee})"
    }
   ]
  },
  {
   "title": "Issue Status Distribution over Month [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_ADD(date(i.created_date), INTERVAL -DAYOFMONTH(date(i.created_date))+1 DAY) as time,\r\n  count(distinct case when status != 'DONE' then i.id else null end) as \"Number of Open Issues\",\r\n  count(distinct case when status = 'DONE' then i.id else null end) as \"Number of Delivered Issues\"\r\nFROM issues i\r\n\tjoin board_issues bi on i.id = bi.issue_id\r\n\tjoin boards b on bi.board_id = b.id\r\nwhere \r\n  i.type in (${type})\r\n  and $__timeFilter(i.created_date)\r\n  and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n  and i.assignee_name in (${assignee})\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _requirements as(\r\n  select\r\n    count(distinct i.id) as total_count,\r\n    count(distinct case when i.status = 'DONE' then i.id else null end) as delivered_count\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in (${type})\r\n    and $__timeFilter(i.created_date)\r\n    and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n    and i.assignee_name in (${assignee})\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirements"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate over Time [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\r\n  select\r\n    DATE_ADD(date(i.created_date), INTERVAL -DAYOFMONTH(date(i.created_date))+1 DAY) as time,\r\n    1.0 * count(distinct case when i.status = 'DONE' then i.id else null end)/count(distinct i.id) as delivered_rate\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in (${type})\r\n    and $__timeFilter(i.created_date)\r\n    and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n    and i.assignee_name in (${assignee})\r\n  group by 1\r\n)\r\n\r\nselect\r\n  time,\r\n  delivered_rate\r\nfrom _requirements\r\norder by time"
    }
   ]
  },
  { "title": "2. Issue Lead Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  avg(lead_time_minutes/1440) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in (${type})\r\n  and i.status = 'DONE'\r\n  and $__timeFilter(i.resolution_date)\r\n  and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n  and i.assignee_name in (${assignee})"
    }
   ]
  },
  {
   "title": "80% Issues' Lead Time are less than # days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    i.lead_time_minutes,\r\n    percent_rank() over (order by lead_time_minutes asc) as ranks\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in (${type})\r\n    and i.status = 'DONE'\r\n    and $__timeFilter(i.resolution_date)\r\n    and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n    and i.assignee_name in (${assignee})\r\n)\r\n\r\nselect\r\n  max(lead_time_minutes/1440) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Mean Issue Lead Time [Issues Resolved in Select Time Range]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\r\n  select \r\n    DATE_ADD(date(i.resolution_date), INTERVAL -DAYOFMONTH(date(i.resolution_date))+1 DAY) as time,\r\n    avg(lead_time_minutes/1440) as mean_lead_time\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in (${type})\r\n    and i.status = 'DONE'\r\n    and $__timeFilter(i.resolution_date)\r\n    and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n    and i.assignee_name in (${assignee})\r\n  group by 1\r\n)\r\n\r\nselect \r\n  date_format(time,'%M %Y') as month,\r\n  mean_lead_time\r\nfrom _requirements\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Cumulative Distribution of Requirement Lead Time [Issues Resolved in Select Time Range]",
   "type": "barchart",
   "description": "1. The cumulative distribution of requirement lead time. \n2. Each point refers to the percent rank of a lead time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    round(i.lead_time_minutes/1440) as lead_time_day\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in (${type})\r\n    and i.status = 'DONE'\r\n    and $__timeFilter(i.resolution_date)\r\n    and bi.board_id in (${board_id})\n  and bi.board_id in (select pm.row_id from project_mapping pm where pm.table = 'boards' and pm.project_name in (${project}))\r\n    and i.assignee_name in (${assignee})\r\n  order by lead_time_day asc\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\r\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   }
  }
 ]
}