{
 "title": "Where is time spent on the path to production?",
 "description": "Commit to Deploy Flow Time",
 "tags": [
  "Perspective: The Path to Production",
  "Unit of Work: Pull Requests"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "interval",
    "label": "Observation window",
    "query": "One Month : DAYOFMONTH, One Week : WEEKDAY, One Day :  DAY"
   }
  ]
 },
 "panels": [
  {
   "title": "How long does it take for changes on a branch to reach production?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. Lead Time for Changes: from initial commit to deployed ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 1, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (\n  SELECT\n    pr.id,\n    pr.merged_date AS pr_merged_date,\n  \n    COALESCE(prm.pr_cycle_time/1440, 0) AS cycle_time\n  FROM pull_requests pr\n  -- if a pr does not have a metrics row, we will drop this from the trend rather than skwing this with a zero. We will report on data quality separately, \n  JOIN project_pr_metrics prm ON pr.id = prm.id\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\n  WHERE\n    $__timeFilter(pr.merged_date)\n    AND pm.project_name IN (${project})\n  GROUP BY 1,2,3\n)\nSELECT \n  CASE \n    WHEN '${interval}' = 'DAY' THEN DATE(pr_merged_date)\n    ELSE DATE_ADD(DATE(pr_merged_date), INTERVAL - $interval(DATE(pr_merged_date)) + 1 DAY) \n  END AS time,\n  AVG(cycle_time) AS 'lead_time_for_changes',\n  Count(_prs.id) as 'count'\nFROM _prs\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Where is time spent in this process? ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Coding Time: From initial commit to PR raised",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 1, "y": 9 },
     "targets": [
      {
       "rawSql": "WITH _prs AS (\n  SELECT\n    pr.id,\n    pr.merged_date AS pr_merged_date,\n    -- Correcting from minutes to days (/1440 instead of /60)\n    COALESCE(prm.pr_coding_time/1440, 0) AS coding_time\n  FROM pull_requests pr\n  JOIN project_pr_metrics prm ON pr.id = prm.id\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\n  WHERE\n    $__timeFilter(pr.merged_date)\n    AND pm.project_name IN (${project})\n  GROUP BY 1,2,3\n)\nSELECT \n  CASE \n    WHEN '${interval}' = 'DAY' THEN DATE(pr_merged_date)\n    ELSE DATE_ADD(DATE(pr_merged_date), INTERVAL - $interval(DATE(pr_merged_date)) + 1 DAY) \n  END AS time,\n  AVG(coding_time) AS 'coding_time'\nFROM _prs\nGROUP BY 1\nORDER BY 1;\n"
      }
     ]
    },
    {
     "title": "Avg. Time to Merge: From PR raised to PR merged",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 1, "y": 17 },
     "targets": [
      {
       "rawSql": "WITH _prs AS (\n  SELECT\n    pr.id,\n    prm.pr_created_date,\n    prm.pr_merged_date\n  FROM pull_requests pr\n  JOIN project_pr_metrics prm ON pr.id = prm.id\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\n  WHERE\n    $__timeFilter(pr.merged_date)\n    AND pm.project_name IN (${project})\n  GROUP BY 1,2,3\n)\nSELECT \n  CASE \n    WHEN '${interval}' = 'DAY' THEN DATE(pr_merged_date)\n    ELSE DATE_ADD(DATE(pr_merged_date), INTERVAL - $interval(DATE(pr_merged_date)) + 1 DAY) \n  END AS time,\n  AVG(TIMESTAMPDIFF(MINUTE, pr_created_date, pr_merged_date) / 1440) AS 'time_to_merge'\nFROM _prs\nGROUP BY 1\nORDER BY 1;\n"
      }
     ]
    },
    {
     "title": "Avg. Time to Deploy: From PR merged to changes deployed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 1, "y": 24 },
     "targets": [
      {
       "rawSql": "WITH _prs AS (\n  SELECT\n    pr.id,\n    pr.merged_date AS pr_merged_date,\n    -- Correcting from minutes to days (/1440 instead of /60)\n    COALESCE(prm.pr_deploy_time/1440, 0) AS deploy_time\n  FROM pull_requests pr\n  LEFT JOIN project_pr_metrics prm ON pr.id = prm.id\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\n  WHERE\n    $__timeFilter(pr.merged_date)\n    AND pm.project_name IN (${project})\n  GROUP BY 1,2,3\n)\nSELECT \n  CASE \n    WHEN '${interval}' = 'DAY' THEN DATE(pr_merged_date)\n    ELSE DATE_ADD(DATE(pr_merged_date), INTERVAL - $interval(DATE(pr_merged_date)) + 1 DAY) \n  END AS time,\n  AVG(deploy_time) AS 'time_to_deploy'\nFROM _prs\nGROUP BY 1\nORDER BY 1;\n"
      }
     ]
    }
   ]
  }
 ]
}